### ISSUE TITLE
Issue with Sources

### ISSUE THREAD

**Issue by thededman** [IkerGarcia/PocketInstaller#1]
Good Evening,
I have added the additional Sources and update but with errors.

GPG error http://pkg.bunsenlabs.org bunsen-hydrogen InRelease
Following signature could not be verified because the public key is not available. 

Same with jessie-backports InRelease as well.

I have re-flashed my pocket and reinstall Marshmallow and tried again.  I get the error during **sudo apt-get update** but do ignore then run sudo apt-get YAD installs fine.

*Figure I'd report as other may see that as well.

**Comment by IkerGarcia** [comment]
Hi, 

Thank you for the report. I probably made a mistake during the creation of the repo, I believe that only with the other deb repo is enough to get YAD. I'll check it and correct the how-to in the next commit.

Thank you for the feedback, we have a lot of room to improve and it's really useful.
